//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using NsbSamplesSqlOutbox.HelperClasses;
using NsbSamplesSqlOutbox.FactoryClasses;
using NsbSamplesSqlOutbox.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Error'.<br/><br/></summary>
	[Serializable]
	public partial class ErrorEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ErrorEntityStaticMetaData _staticMetaData = new ErrorEntityStaticMetaData();
		private static ErrorRelations _relationsFactory = new ErrorRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ErrorEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ErrorEntityStaticMetaData()
			{
				SetEntityCoreInfo("ErrorEntity", InheritanceHierarchyType.None, false, (int)NsbSamplesSqlOutbox.EntityType.ErrorEntity, typeof(ErrorEntity), typeof(ErrorEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static ErrorEntity()
		{
		}

		/// <summary> CTor</summary>
		public ErrorEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ErrorEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ErrorEntity</param>
		public ErrorEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Error which data should be fetched into this Error object</param>
		public ErrorEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Error which data should be fetched into this Error object</param>
		/// <param name="validator">The custom validator object for this ErrorEntity</param>
		public ErrorEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ErrorEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ErrorEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ErrorRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Body property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."Body".<br/>Table field type characteristics (type, precision, scale, length): VarBinary, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.Byte[] Body
		{
			get { return (System.Byte[])GetValue((int)ErrorFieldIndex.Body, true); }
			set	{ SetValue((int)ErrorFieldIndex.Body, value); }
		}

		/// <summary>The CorrelationId property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."CorrelationId".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CorrelationId
		{
			get { return (System.String)GetValue((int)ErrorFieldIndex.CorrelationId, true); }
			set	{ SetValue((int)ErrorFieldIndex.CorrelationId, value); }
		}

		/// <summary>The Expires property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."Expires".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Expires
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ErrorFieldIndex.Expires, false); }
			set	{ SetValue((int)ErrorFieldIndex.Expires, value); }
		}

		/// <summary>The Headers property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."Headers".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Headers
		{
			get { return (System.String)GetValue((int)ErrorFieldIndex.Headers, true); }
			set	{ SetValue((int)ErrorFieldIndex.Headers, value); }
		}

		/// <summary>The Id property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."Id".<br/>Table field type characteristics (type, precision, scale, length): UniqueIdentifier, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)ErrorFieldIndex.Id, true); }
			set	{ SetValue((int)ErrorFieldIndex.Id, value); }
		}

		/// <summary>The Recoverable property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."Recoverable".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Recoverable
		{
			get { return (System.Boolean)GetValue((int)ErrorFieldIndex.Recoverable, true); }
			set	{ SetValue((int)ErrorFieldIndex.Recoverable, value); }
		}

		/// <summary>The ReplyToAddress property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."ReplyToAddress".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ReplyToAddress
		{
			get { return (System.String)GetValue((int)ErrorFieldIndex.ReplyToAddress, true); }
			set	{ SetValue((int)ErrorFieldIndex.ReplyToAddress, value); }
		}

		/// <summary>The RowVersion property of the Entity Error<br/><br/></summary>
		/// <remarks>Mapped on  table field: "error"."RowVersion".<br/>Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, true</remarks>
		public virtual System.Int64 RowVersion
		{
			get { return (System.Int64)GetValue((int)ErrorFieldIndex.RowVersion, true); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace NsbSamplesSqlOutbox
{
	public enum ErrorFieldIndex
	{
		///<summary>Body. </summary>
		Body,
		///<summary>CorrelationId. </summary>
		CorrelationId,
		///<summary>Expires. </summary>
		Expires,
		///<summary>Headers. </summary>
		Headers,
		///<summary>Id. </summary>
		Id,
		///<summary>Recoverable. </summary>
		Recoverable,
		///<summary>ReplyToAddress. </summary>
		ReplyToAddress,
		///<summary>RowVersion. </summary>
		RowVersion,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace NsbSamplesSqlOutbox.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Error. </summary>
	public partial class ErrorRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticErrorRelations
	{

		/// <summary>CTor</summary>
		static StaticErrorRelations() { }
	}
}
