//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using NsbSamplesSqlOutbox.HelperClasses;
using NsbSamplesSqlOutbox.FactoryClasses;
using NsbSamplesSqlOutbox.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'OutboxData1'.<br/><br/></summary>
	[Serializable]
	public partial class OutboxData1Entity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OutboxData1EntityStaticMetaData _staticMetaData = new OutboxData1EntityStaticMetaData();
		private static OutboxData1Relations _relationsFactory = new OutboxData1Relations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OutboxData1EntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OutboxData1EntityStaticMetaData()
			{
				SetEntityCoreInfo("OutboxData1Entity", InheritanceHierarchyType.None, false, (int)NsbSamplesSqlOutbox.EntityType.OutboxData1Entity, typeof(OutboxData1Entity), typeof(OutboxData1EntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static OutboxData1Entity()
		{
		}

		/// <summary> CTor</summary>
		public OutboxData1Entity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OutboxData1Entity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OutboxData1Entity</param>
		public OutboxData1Entity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="messageId">PK value for OutboxData1 which data should be fetched into this OutboxData1 object</param>
		public OutboxData1Entity(System.String messageId) : this(messageId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="messageId">PK value for OutboxData1 which data should be fetched into this OutboxData1 object</param>
		/// <param name="validator">The custom validator object for this OutboxData1Entity</param>
		public OutboxData1Entity(System.String messageId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.MessageId = messageId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OutboxData1Entity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OutboxData1Entity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OutboxData1Relations Relations { get { return _relationsFactory; } }

		/// <summary>The Dispatched property of the Entity OutboxData1<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OutboxData"."Dispatched".<br/>Table field type characteristics (type, precision, scale, length): Bit, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Dispatched
		{
			get { return (System.Boolean)GetValue((int)OutboxData1FieldIndex.Dispatched, true); }
			set	{ SetValue((int)OutboxData1FieldIndex.Dispatched, value); }
		}

		/// <summary>The DispatchedAt property of the Entity OutboxData1<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OutboxData"."DispatchedAt".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DispatchedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OutboxData1FieldIndex.DispatchedAt, false); }
			set	{ SetValue((int)OutboxData1FieldIndex.DispatchedAt, value); }
		}

		/// <summary>The MessageId property of the Entity OutboxData1<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OutboxData"."MessageId".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String MessageId
		{
			get { return (System.String)GetValue((int)OutboxData1FieldIndex.MessageId, true); }
			set	{ SetValue((int)OutboxData1FieldIndex.MessageId, value); }
		}

		/// <summary>The Operations property of the Entity OutboxData1<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OutboxData"."Operations".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Operations
		{
			get { return (System.String)GetValue((int)OutboxData1FieldIndex.Operations, true); }
			set	{ SetValue((int)OutboxData1FieldIndex.Operations, value); }
		}

		/// <summary>The PersistenceVersion property of the Entity OutboxData1<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OutboxData"."PersistenceVersion".<br/>Table field type characteristics (type, precision, scale, length): VarChar, 0, 0, 23.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String PersistenceVersion
		{
			get { return (System.String)GetValue((int)OutboxData1FieldIndex.PersistenceVersion, true); }
			set	{ SetValue((int)OutboxData1FieldIndex.PersistenceVersion, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace NsbSamplesSqlOutbox
{
	public enum OutboxData1FieldIndex
	{
		///<summary>Dispatched. </summary>
		Dispatched,
		///<summary>DispatchedAt. </summary>
		DispatchedAt,
		///<summary>MessageId. </summary>
		MessageId,
		///<summary>Operations. </summary>
		Operations,
		///<summary>PersistenceVersion. </summary>
		PersistenceVersion,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace NsbSamplesSqlOutbox.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OutboxData1. </summary>
	public partial class OutboxData1Relations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOutboxData1Relations
	{

		/// <summary>CTor</summary>
		static StaticOutboxData1Relations() { }
	}
}
