//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using NsbSamplesSqlOutbox.HelperClasses;
using NsbSamplesSqlOutbox.FactoryClasses;
using NsbSamplesSqlOutbox.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'SamplesSqlOutboxReceiverDelayed'.<br/><br/></summary>
	[Serializable]
	public partial class SamplesSqlOutboxReceiverDelayedEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static SamplesSqlOutboxReceiverDelayedEntityStaticMetaData _staticMetaData = new SamplesSqlOutboxReceiverDelayedEntityStaticMetaData();
		private static SamplesSqlOutboxReceiverDelayedRelations _relationsFactory = new SamplesSqlOutboxReceiverDelayedRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SamplesSqlOutboxReceiverDelayedEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SamplesSqlOutboxReceiverDelayedEntityStaticMetaData()
			{
				SetEntityCoreInfo("SamplesSqlOutboxReceiverDelayedEntity", InheritanceHierarchyType.None, false, (int)NsbSamplesSqlOutbox.EntityType.SamplesSqlOutboxReceiverDelayedEntity, typeof(SamplesSqlOutboxReceiverDelayedEntity), typeof(SamplesSqlOutboxReceiverDelayedEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SamplesSqlOutboxReceiverDelayedEntity()
		{
		}

		/// <summary> CTor</summary>
		public SamplesSqlOutboxReceiverDelayedEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SamplesSqlOutboxReceiverDelayedEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SamplesSqlOutboxReceiverDelayedEntity</param>
		public SamplesSqlOutboxReceiverDelayedEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="due">PK value for SamplesSqlOutboxReceiverDelayed which data should be fetched into this SamplesSqlOutboxReceiverDelayed object</param>
		public SamplesSqlOutboxReceiverDelayedEntity(System.DateTime due) : this(due, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="due">PK value for SamplesSqlOutboxReceiverDelayed which data should be fetched into this SamplesSqlOutboxReceiverDelayed object</param>
		/// <param name="validator">The custom validator object for this SamplesSqlOutboxReceiverDelayedEntity</param>
		public SamplesSqlOutboxReceiverDelayedEntity(System.DateTime due, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Due = due;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SamplesSqlOutboxReceiverDelayedEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SamplesSqlOutboxReceiverDelayedEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SamplesSqlOutboxReceiverDelayedRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Body property of the Entity SamplesSqlOutboxReceiverDelayed<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Samples.SqlOutbox.Receiver.Delayed"."Body".<br/>Table field type characteristics (type, precision, scale, length): VarBinary, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.Byte[] Body
		{
			get { return (System.Byte[])GetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Body, true); }
			set	{ SetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Body, value); }
		}

		/// <summary>The Due property of the Entity SamplesSqlOutboxReceiverDelayed<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Samples.SqlOutbox.Receiver.Delayed"."Due".<br/>Table field type characteristics (type, precision, scale, length): DateTime, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.DateTime Due
		{
			get { return (System.DateTime)GetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Due, true); }
			set	{ SetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Due, value); }
		}

		/// <summary>The Headers property of the Entity SamplesSqlOutboxReceiverDelayed<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Samples.SqlOutbox.Receiver.Delayed"."Headers".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Headers
		{
			get { return (System.String)GetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Headers, true); }
			set	{ SetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.Headers, value); }
		}

		/// <summary>The RowVersion property of the Entity SamplesSqlOutboxReceiverDelayed<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Samples.SqlOutbox.Receiver.Delayed"."RowVersion".<br/>Table field type characteristics (type, precision, scale, length): BigInt, 19, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, true</remarks>
		public virtual System.Int64 RowVersion
		{
			get { return (System.Int64)GetValue((int)SamplesSqlOutboxReceiverDelayedFieldIndex.RowVersion, true); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace NsbSamplesSqlOutbox
{
	public enum SamplesSqlOutboxReceiverDelayedFieldIndex
	{
		///<summary>Body. </summary>
		Body,
		///<summary>Due. </summary>
		Due,
		///<summary>Headers. </summary>
		Headers,
		///<summary>RowVersion. </summary>
		RowVersion,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace NsbSamplesSqlOutbox.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SamplesSqlOutboxReceiverDelayed. </summary>
	public partial class SamplesSqlOutboxReceiverDelayedRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSamplesSqlOutboxReceiverDelayedRelations
	{

		/// <summary>CTor</summary>
		static StaticSamplesSqlOutboxReceiverDelayedRelations() { }
	}
}
