//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using NsbSamplesSqlOutbox.HelperClasses;
using NsbSamplesSqlOutbox.FactoryClasses;
using NsbSamplesSqlOutbox.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'SubmittedOrder'.<br/><br/></summary>
	[Serializable]
	public partial class SubmittedOrderEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static SubmittedOrderEntityStaticMetaData _staticMetaData = new SubmittedOrderEntityStaticMetaData();
		private static SubmittedOrderRelations _relationsFactory = new SubmittedOrderRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SubmittedOrderEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SubmittedOrderEntityStaticMetaData()
			{
				SetEntityCoreInfo("SubmittedOrderEntity", InheritanceHierarchyType.None, false, (int)NsbSamplesSqlOutbox.EntityType.SubmittedOrderEntity, typeof(SubmittedOrderEntity), typeof(SubmittedOrderEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SubmittedOrderEntity()
		{
		}

		/// <summary> CTor</summary>
		public SubmittedOrderEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SubmittedOrderEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SubmittedOrderEntity</param>
		public SubmittedOrderEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SubmittedOrder which data should be fetched into this SubmittedOrder object</param>
		public SubmittedOrderEntity(System.Guid id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SubmittedOrder which data should be fetched into this SubmittedOrder object</param>
		/// <param name="validator">The custom validator object for this SubmittedOrderEntity</param>
		public SubmittedOrderEntity(System.Guid id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SubmittedOrderEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SubmittedOrderEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SubmittedOrderRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity SubmittedOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SubmittedOrder"."Id".<br/>Table field type characteristics (type, precision, scale, length): UniqueIdentifier, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid Id
		{
			get { return (System.Guid)GetValue((int)SubmittedOrderFieldIndex.Id, true); }
			set	{ SetValue((int)SubmittedOrderFieldIndex.Id, value); }
		}

		/// <summary>The Value property of the Entity SubmittedOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "SubmittedOrder"."Value".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Value
		{
			get { return (System.Int32)GetValue((int)SubmittedOrderFieldIndex.Value, true); }
			set	{ SetValue((int)SubmittedOrderFieldIndex.Value, value); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace NsbSamplesSqlOutbox
{
	public enum SubmittedOrderFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Value. </summary>
		Value,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace NsbSamplesSqlOutbox.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SubmittedOrder. </summary>
	public partial class SubmittedOrderRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSubmittedOrderRelations
	{

		/// <summary>CTor</summary>
		static StaticSubmittedOrderRelations() { }
	}
}
