//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitErrorEntityMappings();
			InitOutboxDataEntityMappings();
			InitSamplesSqlOutboxReceiverEntityMappings();
			InitSamplesSqlOutboxReceiverDelayedEntityMappings();
			InitSubmittedOrderEntityMappings();
			InitSubscriptionDataEntityMappings();
			InitOutboxData1EntityMappings();
			InitSamplesSqlOutboxSenderEntityMappings();
			InitSamplesSqlOutboxSenderDelayedEntityMappings();
			InitSubscriptionData1EntityMappings();
		}

		/// <summary>Inits ErrorEntity's mappings</summary>
		private void InitErrorEntityMappings()
		{
			this.AddElementMapping("ErrorEntity", @"NsbSamplesSqlOutbox", @"dbo", "error", 8, 0);
			this.AddElementFieldMapping("ErrorEntity", "Body", "Body", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("ErrorEntity", "CorrelationId", "CorrelationId", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ErrorEntity", "Expires", "Expires", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("ErrorEntity", "Headers", "Headers", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("ErrorEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("ErrorEntity", "Recoverable", "Recoverable", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("ErrorEntity", "ReplyToAddress", "ReplyToAddress", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("ErrorEntity", "RowVersion", "RowVersion", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 7);
		}

		/// <summary>Inits OutboxDataEntity's mappings</summary>
		private void InitOutboxDataEntityMappings()
		{
			this.AddElementMapping("OutboxDataEntity", @"NsbSamplesSqlOutbox", @"receiver", "OutboxData", 5, 0);
			this.AddElementFieldMapping("OutboxDataEntity", "Dispatched", "Dispatched", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 0);
			this.AddElementFieldMapping("OutboxDataEntity", "DispatchedAt", "DispatchedAt", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("OutboxDataEntity", "MessageId", "MessageId", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("OutboxDataEntity", "Operations", "Operations", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("OutboxDataEntity", "PersistenceVersion", "PersistenceVersion", false, "VarChar", 23, 0, 0, false, "", null, typeof(System.String), 4);
		}

		/// <summary>Inits SamplesSqlOutboxReceiverEntity's mappings</summary>
		private void InitSamplesSqlOutboxReceiverEntityMappings()
		{
			this.AddElementMapping("SamplesSqlOutboxReceiverEntity", @"NsbSamplesSqlOutbox", @"receiver", "Samples.SqlOutbox.Receiver", 8, 0);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "Body", "Body", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "CorrelationId", "CorrelationId", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "Expires", "Expires", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "Headers", "Headers", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "Recoverable", "Recoverable", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "ReplyToAddress", "ReplyToAddress", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverEntity", "RowVersion", "RowVersion", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 7);
		}

		/// <summary>Inits SamplesSqlOutboxReceiverDelayedEntity's mappings</summary>
		private void InitSamplesSqlOutboxReceiverDelayedEntityMappings()
		{
			this.AddElementMapping("SamplesSqlOutboxReceiverDelayedEntity", @"NsbSamplesSqlOutbox", @"receiver", "Samples.SqlOutbox.Receiver.Delayed", 4, 0);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverDelayedEntity", "Body", "Body", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverDelayedEntity", "Due", "Due", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverDelayedEntity", "Headers", "Headers", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SamplesSqlOutboxReceiverDelayedEntity", "RowVersion", "RowVersion", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 3);
		}

		/// <summary>Inits SubmittedOrderEntity's mappings</summary>
		private void InitSubmittedOrderEntityMappings()
		{
			this.AddElementMapping("SubmittedOrderEntity", @"NsbSamplesSqlOutbox", @"receiver", "SubmittedOrder", 2, 0);
			this.AddElementFieldMapping("SubmittedOrderEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("SubmittedOrderEntity", "Value", "Value", false, "Int", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
		}

		/// <summary>Inits SubscriptionDataEntity's mappings</summary>
		private void InitSubscriptionDataEntityMappings()
		{
			this.AddElementMapping("SubscriptionDataEntity", @"NsbSamplesSqlOutbox", @"receiver", "SubscriptionData", 4, 0);
			this.AddElementFieldMapping("SubscriptionDataEntity", "Endpoint", "Endpoint", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SubscriptionDataEntity", "MessageType", "MessageType", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SubscriptionDataEntity", "PersistenceVersion", "PersistenceVersion", false, "VarChar", 23, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SubscriptionDataEntity", "Subscriber", "Subscriber", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits OutboxData1Entity's mappings</summary>
		private void InitOutboxData1EntityMappings()
		{
			this.AddElementMapping("OutboxData1Entity", @"NsbSamplesSqlOutbox", @"sender", "OutboxData", 5, 0);
			this.AddElementFieldMapping("OutboxData1Entity", "Dispatched", "Dispatched", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 0);
			this.AddElementFieldMapping("OutboxData1Entity", "DispatchedAt", "DispatchedAt", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("OutboxData1Entity", "MessageId", "MessageId", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("OutboxData1Entity", "Operations", "Operations", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("OutboxData1Entity", "PersistenceVersion", "PersistenceVersion", false, "VarChar", 23, 0, 0, false, "", null, typeof(System.String), 4);
		}

		/// <summary>Inits SamplesSqlOutboxSenderEntity's mappings</summary>
		private void InitSamplesSqlOutboxSenderEntityMappings()
		{
			this.AddElementMapping("SamplesSqlOutboxSenderEntity", @"NsbSamplesSqlOutbox", @"sender", "Samples.SqlOutbox.Sender", 8, 0);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "Body", "Body", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "CorrelationId", "CorrelationId", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "Expires", "Expires", true, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "Headers", "Headers", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "Id", "Id", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 4);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "Recoverable", "Recoverable", false, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 5);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "ReplyToAddress", "ReplyToAddress", true, "VarChar", 255, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderEntity", "RowVersion", "RowVersion", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 7);
		}

		/// <summary>Inits SamplesSqlOutboxSenderDelayedEntity's mappings</summary>
		private void InitSamplesSqlOutboxSenderDelayedEntityMappings()
		{
			this.AddElementMapping("SamplesSqlOutboxSenderDelayedEntity", @"NsbSamplesSqlOutbox", @"sender", "Samples.SqlOutbox.Sender.Delayed", 4, 0);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderDelayedEntity", "Body", "Body", true, "VarBinary", 2147483647, 0, 0, false, "", null, typeof(System.Byte[]), 0);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderDelayedEntity", "Due", "Due", false, "DateTime", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderDelayedEntity", "Headers", "Headers", false, "NVarChar", 2147483647, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SamplesSqlOutboxSenderDelayedEntity", "RowVersion", "RowVersion", false, "BigInt", 0, 19, 0, true, "SCOPE_IDENTITY()", null, typeof(System.Int64), 3);
		}

		/// <summary>Inits SubscriptionData1Entity's mappings</summary>
		private void InitSubscriptionData1EntityMappings()
		{
			this.AddElementMapping("SubscriptionData1Entity", @"NsbSamplesSqlOutbox", @"sender", "SubscriptionData", 4, 0);
			this.AddElementFieldMapping("SubscriptionData1Entity", "Endpoint", "Endpoint", true, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SubscriptionData1Entity", "MessageType", "MessageType", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SubscriptionData1Entity", "PersistenceVersion", "PersistenceVersion", false, "VarChar", 23, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SubscriptionData1Entity", "Subscriber", "Subscriber", false, "NVarChar", 200, 0, 0, false, "", null, typeof(System.String), 3);
		}

	}
}
