//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace NsbSamplesSqlOutbox
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Error</summary>
		ErrorEntity,
		///<summary>OutboxData</summary>
		OutboxDataEntity,
		///<summary>SamplesSqlOutboxReceiver</summary>
		SamplesSqlOutboxReceiverEntity,
		///<summary>SamplesSqlOutboxReceiverDelayed</summary>
		SamplesSqlOutboxReceiverDelayedEntity,
		///<summary>SubmittedOrder</summary>
		SubmittedOrderEntity,
		///<summary>SubscriptionData</summary>
		SubscriptionDataEntity,
		///<summary>OutboxData1</summary>
		OutboxData1Entity,
		///<summary>SamplesSqlOutboxSender</summary>
		SamplesSqlOutboxSenderEntity,
		///<summary>SamplesSqlOutboxSenderDelayed</summary>
		SamplesSqlOutboxSenderDelayedEntity,
		///<summary>SubscriptionData1</summary>
		SubscriptionData1Entity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

