//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using NsbSamplesSqlOutbox.EntityClasses;
using NsbSamplesSqlOutbox.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace NsbSamplesSqlOutbox.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the Error entity</summary>
		public EntityQuery<ErrorEntity> Error { get { return Create<ErrorEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OutboxData entity</summary>
		public EntityQuery<OutboxDataEntity> OutboxData { get { return Create<OutboxDataEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SamplesSqlOutboxReceiver entity</summary>
		public EntityQuery<SamplesSqlOutboxReceiverEntity> SamplesSqlOutboxReceiver { get { return Create<SamplesSqlOutboxReceiverEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SamplesSqlOutboxReceiverDelayed entity</summary>
		public EntityQuery<SamplesSqlOutboxReceiverDelayedEntity> SamplesSqlOutboxReceiverDelayed { get { return Create<SamplesSqlOutboxReceiverDelayedEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SubmittedOrder entity</summary>
		public EntityQuery<SubmittedOrderEntity> SubmittedOrder { get { return Create<SubmittedOrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SubscriptionData entity</summary>
		public EntityQuery<SubscriptionDataEntity> SubscriptionData { get { return Create<SubscriptionDataEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OutboxData1 entity</summary>
		public EntityQuery<OutboxData1Entity> OutboxData1 { get { return Create<OutboxData1Entity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SamplesSqlOutboxSender entity</summary>
		public EntityQuery<SamplesSqlOutboxSenderEntity> SamplesSqlOutboxSender { get { return Create<SamplesSqlOutboxSenderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SamplesSqlOutboxSenderDelayed entity</summary>
		public EntityQuery<SamplesSqlOutboxSenderDelayedEntity> SamplesSqlOutboxSenderDelayed { get { return Create<SamplesSqlOutboxSenderDelayedEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SubscriptionData1 entity</summary>
		public EntityQuery<SubscriptionData1Entity> SubscriptionData1 { get { return Create<SubscriptionData1Entity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}