//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.HelperClasses
{
	/// <summary>Field Creation Class for entity ErrorEntity</summary>
	public partial class ErrorFields
	{
		/// <summary>Creates a new ErrorEntity.Body field instance</summary>
		public static EntityField2 Body { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.Body); }}
		/// <summary>Creates a new ErrorEntity.CorrelationId field instance</summary>
		public static EntityField2 CorrelationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.CorrelationId); }}
		/// <summary>Creates a new ErrorEntity.Expires field instance</summary>
		public static EntityField2 Expires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.Expires); }}
		/// <summary>Creates a new ErrorEntity.Headers field instance</summary>
		public static EntityField2 Headers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.Headers); }}
		/// <summary>Creates a new ErrorEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.Id); }}
		/// <summary>Creates a new ErrorEntity.Recoverable field instance</summary>
		public static EntityField2 Recoverable { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.Recoverable); }}
		/// <summary>Creates a new ErrorEntity.ReplyToAddress field instance</summary>
		public static EntityField2 ReplyToAddress { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.ReplyToAddress); }}
		/// <summary>Creates a new ErrorEntity.RowVersion field instance</summary>
		public static EntityField2 RowVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ErrorFieldIndex.RowVersion); }}
	}

	/// <summary>Field Creation Class for entity OutboxDataEntity</summary>
	public partial class OutboxDataFields
	{
		/// <summary>Creates a new OutboxDataEntity.Dispatched field instance</summary>
		public static EntityField2 Dispatched { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxDataFieldIndex.Dispatched); }}
		/// <summary>Creates a new OutboxDataEntity.DispatchedAt field instance</summary>
		public static EntityField2 DispatchedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxDataFieldIndex.DispatchedAt); }}
		/// <summary>Creates a new OutboxDataEntity.MessageId field instance</summary>
		public static EntityField2 MessageId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxDataFieldIndex.MessageId); }}
		/// <summary>Creates a new OutboxDataEntity.Operations field instance</summary>
		public static EntityField2 Operations { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxDataFieldIndex.Operations); }}
		/// <summary>Creates a new OutboxDataEntity.PersistenceVersion field instance</summary>
		public static EntityField2 PersistenceVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxDataFieldIndex.PersistenceVersion); }}
	}

	/// <summary>Field Creation Class for entity SamplesSqlOutboxReceiverEntity</summary>
	public partial class SamplesSqlOutboxReceiverFields
	{
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.Body field instance</summary>
		public static EntityField2 Body { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.Body); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.CorrelationId field instance</summary>
		public static EntityField2 CorrelationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.CorrelationId); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.Expires field instance</summary>
		public static EntityField2 Expires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.Expires); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.Headers field instance</summary>
		public static EntityField2 Headers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.Headers); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.Id); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.Recoverable field instance</summary>
		public static EntityField2 Recoverable { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.Recoverable); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.ReplyToAddress field instance</summary>
		public static EntityField2 ReplyToAddress { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.ReplyToAddress); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverEntity.RowVersion field instance</summary>
		public static EntityField2 RowVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverFieldIndex.RowVersion); }}
	}

	/// <summary>Field Creation Class for entity SamplesSqlOutboxReceiverDelayedEntity</summary>
	public partial class SamplesSqlOutboxReceiverDelayedFields
	{
		/// <summary>Creates a new SamplesSqlOutboxReceiverDelayedEntity.Body field instance</summary>
		public static EntityField2 Body { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverDelayedFieldIndex.Body); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverDelayedEntity.Due field instance</summary>
		public static EntityField2 Due { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverDelayedFieldIndex.Due); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverDelayedEntity.Headers field instance</summary>
		public static EntityField2 Headers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverDelayedFieldIndex.Headers); }}
		/// <summary>Creates a new SamplesSqlOutboxReceiverDelayedEntity.RowVersion field instance</summary>
		public static EntityField2 RowVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxReceiverDelayedFieldIndex.RowVersion); }}
	}

	/// <summary>Field Creation Class for entity SubmittedOrderEntity</summary>
	public partial class SubmittedOrderFields
	{
		/// <summary>Creates a new SubmittedOrderEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubmittedOrderFieldIndex.Id); }}
		/// <summary>Creates a new SubmittedOrderEntity.Value field instance</summary>
		public static EntityField2 Value { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubmittedOrderFieldIndex.Value); }}
	}

	/// <summary>Field Creation Class for entity SubscriptionDataEntity</summary>
	public partial class SubscriptionDataFields
	{
		/// <summary>Creates a new SubscriptionDataEntity.Endpoint field instance</summary>
		public static EntityField2 Endpoint { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionDataFieldIndex.Endpoint); }}
		/// <summary>Creates a new SubscriptionDataEntity.MessageType field instance</summary>
		public static EntityField2 MessageType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionDataFieldIndex.MessageType); }}
		/// <summary>Creates a new SubscriptionDataEntity.PersistenceVersion field instance</summary>
		public static EntityField2 PersistenceVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionDataFieldIndex.PersistenceVersion); }}
		/// <summary>Creates a new SubscriptionDataEntity.Subscriber field instance</summary>
		public static EntityField2 Subscriber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionDataFieldIndex.Subscriber); }}
	}

	/// <summary>Field Creation Class for entity OutboxData1Entity</summary>
	public partial class OutboxData1Fields
	{
		/// <summary>Creates a new OutboxData1Entity.Dispatched field instance</summary>
		public static EntityField2 Dispatched { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxData1FieldIndex.Dispatched); }}
		/// <summary>Creates a new OutboxData1Entity.DispatchedAt field instance</summary>
		public static EntityField2 DispatchedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxData1FieldIndex.DispatchedAt); }}
		/// <summary>Creates a new OutboxData1Entity.MessageId field instance</summary>
		public static EntityField2 MessageId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxData1FieldIndex.MessageId); }}
		/// <summary>Creates a new OutboxData1Entity.Operations field instance</summary>
		public static EntityField2 Operations { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxData1FieldIndex.Operations); }}
		/// <summary>Creates a new OutboxData1Entity.PersistenceVersion field instance</summary>
		public static EntityField2 PersistenceVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OutboxData1FieldIndex.PersistenceVersion); }}
	}

	/// <summary>Field Creation Class for entity SamplesSqlOutboxSenderEntity</summary>
	public partial class SamplesSqlOutboxSenderFields
	{
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.Body field instance</summary>
		public static EntityField2 Body { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.Body); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.CorrelationId field instance</summary>
		public static EntityField2 CorrelationId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.CorrelationId); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.Expires field instance</summary>
		public static EntityField2 Expires { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.Expires); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.Headers field instance</summary>
		public static EntityField2 Headers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.Headers); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.Id); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.Recoverable field instance</summary>
		public static EntityField2 Recoverable { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.Recoverable); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.ReplyToAddress field instance</summary>
		public static EntityField2 ReplyToAddress { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.ReplyToAddress); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderEntity.RowVersion field instance</summary>
		public static EntityField2 RowVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderFieldIndex.RowVersion); }}
	}

	/// <summary>Field Creation Class for entity SamplesSqlOutboxSenderDelayedEntity</summary>
	public partial class SamplesSqlOutboxSenderDelayedFields
	{
		/// <summary>Creates a new SamplesSqlOutboxSenderDelayedEntity.Body field instance</summary>
		public static EntityField2 Body { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderDelayedFieldIndex.Body); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderDelayedEntity.Due field instance</summary>
		public static EntityField2 Due { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderDelayedFieldIndex.Due); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderDelayedEntity.Headers field instance</summary>
		public static EntityField2 Headers { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderDelayedFieldIndex.Headers); }}
		/// <summary>Creates a new SamplesSqlOutboxSenderDelayedEntity.RowVersion field instance</summary>
		public static EntityField2 RowVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SamplesSqlOutboxSenderDelayedFieldIndex.RowVersion); }}
	}

	/// <summary>Field Creation Class for entity SubscriptionData1Entity</summary>
	public partial class SubscriptionData1Fields
	{
		/// <summary>Creates a new SubscriptionData1Entity.Endpoint field instance</summary>
		public static EntityField2 Endpoint { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionData1FieldIndex.Endpoint); }}
		/// <summary>Creates a new SubscriptionData1Entity.MessageType field instance</summary>
		public static EntityField2 MessageType { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionData1FieldIndex.MessageType); }}
		/// <summary>Creates a new SubscriptionData1Entity.PersistenceVersion field instance</summary>
		public static EntityField2 PersistenceVersion { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionData1FieldIndex.PersistenceVersion); }}
		/// <summary>Creates a new SubscriptionData1Entity.Subscriber field instance</summary>
		public static EntityField2 Subscriber { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SubscriptionData1FieldIndex.Subscriber); }}
	}
	

}