//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using NsbSamplesSqlOutbox.FactoryClasses;
using NsbSamplesSqlOutbox.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace NsbSamplesSqlOutbox.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitErrorEntityInfo();
			InitOutboxDataEntityInfo();
			InitSamplesSqlOutboxReceiverEntityInfo();
			InitSamplesSqlOutboxReceiverDelayedEntityInfo();
			InitSubmittedOrderEntityInfo();
			InitSubscriptionDataEntityInfo();
			InitOutboxData1EntityInfo();
			InitSamplesSqlOutboxSenderEntityInfo();
			InitSamplesSqlOutboxSenderDelayedEntityInfo();
			InitSubscriptionData1EntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits ErrorEntity's info objects</summary>
		private void InitErrorEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ErrorFieldIndex), "ErrorEntity");
			this.AddElementFieldInfo("ErrorEntity", "Body", typeof(System.Byte[]), false, false, false, true,  (int)ErrorFieldIndex.Body, 2147483647, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "CorrelationId", typeof(System.String), false, false, false, true,  (int)ErrorFieldIndex.CorrelationId, 255, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "Expires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)ErrorFieldIndex.Expires, 0, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "Headers", typeof(System.String), false, false, false, false,  (int)ErrorFieldIndex.Headers, 2147483647, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)ErrorFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "Recoverable", typeof(System.Boolean), false, false, false, false,  (int)ErrorFieldIndex.Recoverable, 0, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "ReplyToAddress", typeof(System.String), false, false, false, true,  (int)ErrorFieldIndex.ReplyToAddress, 255, 0, 0);
			this.AddElementFieldInfo("ErrorEntity", "RowVersion", typeof(System.Int64), false, false, true, false,  (int)ErrorFieldIndex.RowVersion, 0, 0, 19);
		}

		/// <summary>Inits OutboxDataEntity's info objects</summary>
		private void InitOutboxDataEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OutboxDataFieldIndex), "OutboxDataEntity");
			this.AddElementFieldInfo("OutboxDataEntity", "Dispatched", typeof(System.Boolean), false, false, false, false,  (int)OutboxDataFieldIndex.Dispatched, 0, 0, 0);
			this.AddElementFieldInfo("OutboxDataEntity", "DispatchedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OutboxDataFieldIndex.DispatchedAt, 0, 0, 0);
			this.AddElementFieldInfo("OutboxDataEntity", "MessageId", typeof(System.String), true, false, false, false,  (int)OutboxDataFieldIndex.MessageId, 200, 0, 0);
			this.AddElementFieldInfo("OutboxDataEntity", "Operations", typeof(System.String), false, false, false, false,  (int)OutboxDataFieldIndex.Operations, 2147483647, 0, 0);
			this.AddElementFieldInfo("OutboxDataEntity", "PersistenceVersion", typeof(System.String), false, false, false, false,  (int)OutboxDataFieldIndex.PersistenceVersion, 23, 0, 0);
		}

		/// <summary>Inits SamplesSqlOutboxReceiverEntity's info objects</summary>
		private void InitSamplesSqlOutboxReceiverEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SamplesSqlOutboxReceiverFieldIndex), "SamplesSqlOutboxReceiverEntity");
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "Body", typeof(System.Byte[]), false, false, false, true,  (int)SamplesSqlOutboxReceiverFieldIndex.Body, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "CorrelationId", typeof(System.String), false, false, false, true,  (int)SamplesSqlOutboxReceiverFieldIndex.CorrelationId, 255, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "Expires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SamplesSqlOutboxReceiverFieldIndex.Expires, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "Headers", typeof(System.String), false, false, false, false,  (int)SamplesSqlOutboxReceiverFieldIndex.Headers, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)SamplesSqlOutboxReceiverFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "Recoverable", typeof(System.Boolean), false, false, false, false,  (int)SamplesSqlOutboxReceiverFieldIndex.Recoverable, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "ReplyToAddress", typeof(System.String), false, false, false, true,  (int)SamplesSqlOutboxReceiverFieldIndex.ReplyToAddress, 255, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverEntity", "RowVersion", typeof(System.Int64), false, false, true, false,  (int)SamplesSqlOutboxReceiverFieldIndex.RowVersion, 0, 0, 19);
		}

		/// <summary>Inits SamplesSqlOutboxReceiverDelayedEntity's info objects</summary>
		private void InitSamplesSqlOutboxReceiverDelayedEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SamplesSqlOutboxReceiverDelayedFieldIndex), "SamplesSqlOutboxReceiverDelayedEntity");
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverDelayedEntity", "Body", typeof(System.Byte[]), false, false, false, true,  (int)SamplesSqlOutboxReceiverDelayedFieldIndex.Body, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverDelayedEntity", "Due", typeof(System.DateTime), true, false, false, false,  (int)SamplesSqlOutboxReceiverDelayedFieldIndex.Due, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverDelayedEntity", "Headers", typeof(System.String), false, false, false, false,  (int)SamplesSqlOutboxReceiverDelayedFieldIndex.Headers, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxReceiverDelayedEntity", "RowVersion", typeof(System.Int64), false, false, true, false,  (int)SamplesSqlOutboxReceiverDelayedFieldIndex.RowVersion, 0, 0, 19);
		}

		/// <summary>Inits SubmittedOrderEntity's info objects</summary>
		private void InitSubmittedOrderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SubmittedOrderFieldIndex), "SubmittedOrderEntity");
			this.AddElementFieldInfo("SubmittedOrderEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)SubmittedOrderFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("SubmittedOrderEntity", "Value", typeof(System.Int32), false, false, false, false,  (int)SubmittedOrderFieldIndex.Value, 0, 0, 10);
		}

		/// <summary>Inits SubscriptionDataEntity's info objects</summary>
		private void InitSubscriptionDataEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SubscriptionDataFieldIndex), "SubscriptionDataEntity");
			this.AddElementFieldInfo("SubscriptionDataEntity", "Endpoint", typeof(System.String), false, false, false, true,  (int)SubscriptionDataFieldIndex.Endpoint, 200, 0, 0);
			this.AddElementFieldInfo("SubscriptionDataEntity", "MessageType", typeof(System.String), true, false, false, false,  (int)SubscriptionDataFieldIndex.MessageType, 200, 0, 0);
			this.AddElementFieldInfo("SubscriptionDataEntity", "PersistenceVersion", typeof(System.String), false, false, false, false,  (int)SubscriptionDataFieldIndex.PersistenceVersion, 23, 0, 0);
			this.AddElementFieldInfo("SubscriptionDataEntity", "Subscriber", typeof(System.String), true, false, false, false,  (int)SubscriptionDataFieldIndex.Subscriber, 200, 0, 0);
		}

		/// <summary>Inits OutboxData1Entity's info objects</summary>
		private void InitOutboxData1EntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OutboxData1FieldIndex), "OutboxData1Entity");
			this.AddElementFieldInfo("OutboxData1Entity", "Dispatched", typeof(System.Boolean), false, false, false, false,  (int)OutboxData1FieldIndex.Dispatched, 0, 0, 0);
			this.AddElementFieldInfo("OutboxData1Entity", "DispatchedAt", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)OutboxData1FieldIndex.DispatchedAt, 0, 0, 0);
			this.AddElementFieldInfo("OutboxData1Entity", "MessageId", typeof(System.String), true, false, false, false,  (int)OutboxData1FieldIndex.MessageId, 200, 0, 0);
			this.AddElementFieldInfo("OutboxData1Entity", "Operations", typeof(System.String), false, false, false, false,  (int)OutboxData1FieldIndex.Operations, 2147483647, 0, 0);
			this.AddElementFieldInfo("OutboxData1Entity", "PersistenceVersion", typeof(System.String), false, false, false, false,  (int)OutboxData1FieldIndex.PersistenceVersion, 23, 0, 0);
		}

		/// <summary>Inits SamplesSqlOutboxSenderEntity's info objects</summary>
		private void InitSamplesSqlOutboxSenderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SamplesSqlOutboxSenderFieldIndex), "SamplesSqlOutboxSenderEntity");
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "Body", typeof(System.Byte[]), false, false, false, true,  (int)SamplesSqlOutboxSenderFieldIndex.Body, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "CorrelationId", typeof(System.String), false, false, false, true,  (int)SamplesSqlOutboxSenderFieldIndex.CorrelationId, 255, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "Expires", typeof(Nullable<System.DateTime>), false, false, false, true,  (int)SamplesSqlOutboxSenderFieldIndex.Expires, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "Headers", typeof(System.String), false, false, false, false,  (int)SamplesSqlOutboxSenderFieldIndex.Headers, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "Id", typeof(System.Guid), true, false, false, false,  (int)SamplesSqlOutboxSenderFieldIndex.Id, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "Recoverable", typeof(System.Boolean), false, false, false, false,  (int)SamplesSqlOutboxSenderFieldIndex.Recoverable, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "ReplyToAddress", typeof(System.String), false, false, false, true,  (int)SamplesSqlOutboxSenderFieldIndex.ReplyToAddress, 255, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderEntity", "RowVersion", typeof(System.Int64), false, false, true, false,  (int)SamplesSqlOutboxSenderFieldIndex.RowVersion, 0, 0, 19);
		}

		/// <summary>Inits SamplesSqlOutboxSenderDelayedEntity's info objects</summary>
		private void InitSamplesSqlOutboxSenderDelayedEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SamplesSqlOutboxSenderDelayedFieldIndex), "SamplesSqlOutboxSenderDelayedEntity");
			this.AddElementFieldInfo("SamplesSqlOutboxSenderDelayedEntity", "Body", typeof(System.Byte[]), false, false, false, true,  (int)SamplesSqlOutboxSenderDelayedFieldIndex.Body, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderDelayedEntity", "Due", typeof(System.DateTime), true, false, false, false,  (int)SamplesSqlOutboxSenderDelayedFieldIndex.Due, 0, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderDelayedEntity", "Headers", typeof(System.String), false, false, false, false,  (int)SamplesSqlOutboxSenderDelayedFieldIndex.Headers, 2147483647, 0, 0);
			this.AddElementFieldInfo("SamplesSqlOutboxSenderDelayedEntity", "RowVersion", typeof(System.Int64), false, false, true, false,  (int)SamplesSqlOutboxSenderDelayedFieldIndex.RowVersion, 0, 0, 19);
		}

		/// <summary>Inits SubscriptionData1Entity's info objects</summary>
		private void InitSubscriptionData1EntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SubscriptionData1FieldIndex), "SubscriptionData1Entity");
			this.AddElementFieldInfo("SubscriptionData1Entity", "Endpoint", typeof(System.String), false, false, false, true,  (int)SubscriptionData1FieldIndex.Endpoint, 200, 0, 0);
			this.AddElementFieldInfo("SubscriptionData1Entity", "MessageType", typeof(System.String), true, false, false, false,  (int)SubscriptionData1FieldIndex.MessageType, 200, 0, 0);
			this.AddElementFieldInfo("SubscriptionData1Entity", "PersistenceVersion", typeof(System.String), false, false, false, false,  (int)SubscriptionData1FieldIndex.PersistenceVersion, 23, 0, 0);
			this.AddElementFieldInfo("SubscriptionData1Entity", "Subscriber", typeof(System.String), true, false, false, false,  (int)SubscriptionData1FieldIndex.Subscriber, 200, 0, 0);
		}
	}
}